version: '3.9'

services:

  db:
    image: postgres:16.3-alpine
    container_name: go_db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: fiber-app